id: I5973607E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:54:13+00:00'
last_modified: '2022-06-08T04:36:34.509605+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD109
  title: 中国历史地图集
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C02C:
      image_group_id: I2PD15094
      title: ''
      total_pages: 129
      order: 1
      base_file: C02C.txt
    '7914':
      image_group_id: I2PD15095
      title: ''
      total_pages: 149
      order: 2
      base_file: 7914.txt
    0F06:
      image_group_id: I2PD15096
      title: ''
      total_pages: 139
      order: 3
      base_file: 0F06.txt
    B2E0:
      image_group_id: I2PD15097
      title: ''
      total_pages: 157
      order: 4
      base_file: B2E0.txt
    2FD4:
      image_group_id: I2PD15098
      title: ''
      total_pages: 220
      order: 5
      base_file: 2FD4.txt
    6A78:
      image_group_id: I2PD15099
      title: ''
      total_pages: 191
      order: 6
      base_file: 6A78.txt
    '3472':
      image_group_id: I2PD15100
      title: ''
      total_pages: 231
      order: 7
      base_file: 3472.txt
    5EAA:
      image_group_id: I2PD15101
      title: ''
      total_pages: 197
      order: 8
      base_file: 5EAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
